-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 11:20:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema travelagency
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `travelagency` ;

-- -----------------------------------------------------
-- Schema travelagency
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travelagency` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `travelagency` ;

-- -----------------------------------------------------
-- Table `travelagency`.`destination`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travelagency`.`destination` ;

CREATE TABLE IF NOT EXISTS `travelagency`.`destination` (
  `idDestination` BIGINT NOT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `destinationName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idDestination`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelagency`.`hibernate_sequence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travelagency`.`hibernate_sequence` ;

CREATE TABLE IF NOT EXISTS `travelagency`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelagency`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travelagency`.`users` ;

CREATE TABLE IF NOT EXISTS `travelagency`.`users` (
  `DTYPE` VARCHAR(31) NOT NULL,
  `id` BIGINT NOT NULL,
  `firstName` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_7e6mbcmjjaslaikwrufbj7jv8` (`password` ASC) VISIBLE,
  UNIQUE INDEX `UK_23y4gd49ajvbqgl3psjsvhff6` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelagency`.`vacationpackage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travelagency`.`vacationpackage` ;

CREATE TABLE IF NOT EXISTS `travelagency`.`vacationpackage` (
  `idVacation` BIGINT NOT NULL,
  `endPeriod` DATE NULL DEFAULT NULL,
  `nrPeopleAllowed` INT NULL DEFAULT NULL,
  `price` BIGINT NULL DEFAULT NULL,
  `startPeriod` DATE NULL DEFAULT NULL,
  `statusVacation` VARCHAR(255) NULL DEFAULT NULL,
  `idDestination` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`idVacation`),
  INDEX `FK6f231ser8s3aqnju705i96j87` (`idDestination` ASC) VISIBLE,
  CONSTRAINT `FK6f231ser8s3aqnju705i96j87`
    FOREIGN KEY (`idDestination`)
    REFERENCES `travelagency`.`destination` (`idDestination`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `travelagency`.`vacationpackage_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travelagency`.`vacationpackage_users` ;

CREATE TABLE IF NOT EXISTS `travelagency`.`vacationpackage_users` (
  `vacations_idVacation` BIGINT NOT NULL,
  `users_id` BIGINT NOT NULL,
  INDEX `FK53rmu1ihtog7f18ss7tt2orqp` (`users_id` ASC) VISIBLE,
  INDEX `FKjujfnddd8fox3kdqfhbvrji0m` (`vacations_idVacation` ASC) VISIBLE,
  CONSTRAINT `FK53rmu1ihtog7f18ss7tt2orqp`
    FOREIGN KEY (`users_id`)
    REFERENCES `travelagency`.`users` (`id`),
  CONSTRAINT `FKjujfnddd8fox3kdqfhbvrji0m`
    FOREIGN KEY (`vacations_idVacation`)
    REFERENCES `travelagency`.`vacationpackage` (`idVacation`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
